export function piTeamsHelp(): string {
	return [
		"pi-teams commands:",
		"",
		"Core:",
		"- Agent can use the `team` tool autonomously; slash commands are manual controls.",
		"- Tool action `recommend` suggests the best team/workflow for a goal.",
		"- /teams — list teams, workflows, agents, recent runs",
		"- /team-run [--team=name] [--workflow=name] [--async] [--worktree] <goal>",
		"- /team-status <runId>",
		"- /team-summary <runId>",
		"- /team-resume <runId>",
		"- /team-cancel <runId>",
		"",
		"Inspection:",
		"- /team-events <runId>",
		"- /team-artifacts <runId>",
		"- /team-worktrees <runId>",
		"- /team-api <runId> <operation> [taskId=<taskId>] [body=<message>]",
		"- /team-dashboard",
		"- /team-manager",
		"",
		"Maintenance:",
		"- /team-cleanup <runId> [--force]",
		"- /team-forget <runId> --confirm [--force]",
		"- /team-prune --keep=20 --confirm",
		"",
		"Portability:",
		"- /team-export <runId>",
		"- /team-import <path-to-run-export.json> [--user]",
		"- /team-imports",
		"",
		"Diagnostics:",
		"- /team-doctor",
		"- /team-init [--copy-builtins] [--overwrite]",
		"- /team-config [key=value] [--unset=key.path] [--project]",
		"- /team-autonomy [status|on|off|manual|suggested|assisted|aggressive] [--prefer-async] [--no-worktree-suggest]",
		"- /team-validate",
		"- /team-help",
		"",
		"Real child workers are disabled by default. Enable with PI_TEAMS_EXECUTE_WORKERS=1 or config executeWorkers=true.",
	].join("\n");
}
